### ISSUE TITLE
[Help needed] TCP server - data not in readable format

### ISSUE THREAD

**Issue by venu-n** [gcjyzdd/Android-Send-Accelerometer-Data-Using-TCP#1]
Ran tcp sever in OSX  (using netcat command, nc -l 31006), started receiving data however its not in readable format.  Can you please help with a suggestion/snippet to receive data in the format you had shown.  

```
TCP SEVER OUTPUT:  @	G?@?hsAbN>????>??Q??????
                                x??׀L@0?u@??DAff>??? >?(Q????}??H?ԱL@&??@???A	K?>??? >?(Q????}??H?ԱL????@??`A?>À??>??Q?????p?@??K??׮@?-A
                                                         ?w>??>??Q???????????L@G?@?A1'>?h???>Q????׀??ـ??ЀL@	X@?"?A
```

**Comment by gcjyzdd** [comment]
Have you tried the pyserver.py script? I used it to receive data.

**Comment by venu-n** [comment]
It worked with pyserver.py script.  Will try to get it worked on ESP8266.   Thanks.
